# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Main CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the branches given below
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies(npm packages)
      run: npm ci

    - name: Lint using ESLint
      run: npm run lint

    - name: Format using Prettier
      run: npm run format

    # Todo: integrate any testing library to run here
    # - name: Test
    #   run: npm test

    - name: Vite build
      run: npm run build --if-present
